version: "3.8"
services:

  postgres:
    image: postgres:13.4-alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES__PASSWORD}
      POSTGRES_USER: ${POSTGRES__USER}
      POSTGRES_DB: ${POSTGRES__NAME}
    ports:
      - ${POSTGRES__PORT}:${POSTGRES__PORT}
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
      - ./data/postgres/:/var/lib/postgresql/data
    healthcheck :
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES__NAME}", "-U", "${POSTGRES__USER}" ]
      interval : 5s
      timeout : 5s
      retries : 5

  adminer:
    image: adminer
    ports:
    - 8080:8080
    depends_on :
      postgres:
        condition: service_healthy

  bot:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/opt/bender
    links:
      - postgres
    depends_on :
      postgres:
        condition: service_healthy
