version: "3.8"
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env

  bot:
    build: .
    volumes:
      - .:/opt/wiki_bot
    ports:
      - "8000:5000"
    env_file:
      - .env
    depends_on:
      - db
