version: "3.8"
services:
  redis:
    image: redis:6-alpine
    env_file:
      - .env
    environment:
      REDIS_HOST: ${REDIS__HOST}
      VOLUMES_DIR: ~/{VOLUMES_DIR}
    ports:
      - 6379:6379
    volumes:
      - ~/${VOLUMES_DIR}/redis-config:/usr/local/etc/redis/redis.conf
      - ~/${VOLUMES_DIR}/redis-data:/data
    command: "redis-server /usr/local/etc/redis/redis.conf"
    restart: "unless-stopped"

  bot:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    volumes:
      - .:/bender_bot
    stop_signal: SIGINT
    restart: "unless-stopped"
