"""Initial migration

Revision ID: 438d24d1d63a
Revises: 
Create Date: 2022-08-28 21:02:04.773927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438d24d1d63a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
