"""empty message

Revision ID: f3636fdd5219
Revises: 
Create Date: 2022-09-25 14:21:54.989420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3636fdd5219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('customer_nickname', sa.String(), nullable=True),
    sa.Column('customer_full_name', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer')),
    sa.UniqueConstraint('customer_id', name=op.f('uq_customer_customer_id'))
    )
    op.create_table('quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation', sa.Text(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('from_user', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('is_confirmed', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_user'], ['customer.id'], name=op.f('fk_quote_from_user_customer')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quote'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quote')
    op.drop_table('customer')
    # ### end Alembic commands ###
